# Generated by Django 3.2.7 on 2022-06-12 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='domain')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'fs_domain',
            },
        ),
        migrations.CreateModel(
            name='FsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('provider_type', models.CharField(help_text='ex. DID , Termimation', max_length=20, verbose_name='Provider Type')),
                ('acl', models.CharField(help_text='command separate IP', max_length=200, verbose_name='IP Access List')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'fs_provider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='domain')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Cell Phonenumbers')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FS User',
                'verbose_name_plural': 'FS Users',
                'db_table': 'fs_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FsDidNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='DID Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('did_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipuser.fsprovider')),
                ('domain', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='sipuser.domain')),
            ],
            options={
                'verbose_name': 'DID Number',
                'verbose_name_plural': 'DID Numbers',
                'db_table': 'fs_didnumber',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sip_username', models.CharField(max_length=100, verbose_name='SIP Username')),
                ('sip_password', models.CharField(max_length=100, verbose_name='SIP Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('extension_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipuser.fsuser')),
            ],
            options={
                'verbose_name': 'Extension',
                'verbose_name_plural': 'Extensions',
                'db_table': 'fs_extension',
                'managed': True,
            },
        ),
    ]
