# Generated by Django 3.2.7 on 2022-06-12 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='domain name'),
            preserve_default=False,
        ),
    ]
