# Generated by Django 3.2.7 on 2022-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0002_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsdidnumber',
            old_name='did_provider',
            new_name='provider',
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
