# Generated by Django 3.2.7 on 2022-06-12 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sipuser', '0003_auto_20220612_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='extension_user',
        ),
        migrations.AddField(
            model_name='extension',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_user', to='sipuser.fsuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fsdidnumber',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='did_provider', to='sipuser.fsprovider'),
        ),
        migrations.AlterField(
            model_name='fsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
