# Generated by Django 3.2.7 on 2022-06-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0004_auto_20220612_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsuser',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_domain', to='sipuser.domain'),
        ),
    ]
