# Generated by Django 3.2.7 on 2022-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0005_alter_fsuser_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='sip_username',
            field=models.CharField(max_length=100, unique=True, verbose_name='SIP Username'),
        ),
    ]
