# Generated by Django 3.2.7 on 2022-06-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0006_alter_extension_sip_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsdidnumber',
            name='extension',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='sipuser.extension'),
            preserve_default=b'I01\n',
        ),
    ]
