# Generated by Django 3.2.7 on 2022-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0007_fsdidnumber_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsdidnumber',
            name='phonenumber',
            field=models.CharField(max_length=20, unique=True, verbose_name='DID Number'),
        ),
    ]
