# Generated by Django 3.2.7 on 2022-06-19 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0008_alter_fsdidnumber_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FsCDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_uuid', models.CharField(max_length=100)),
                ('call_direction', models.CharField(max_length=50)),
                ('call_from', models.CharField(max_length=50)),
                ('call_to', models.CharField(max_length=50)),
                ('bill_duration', models.IntegerField(max_length=11)),
                ('started_at', models.DateTimeField(null=True)),
                ('answered_at', models.DateTimeField(null=True)),
                ('hangup_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('didnumber', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='sipuser.fsdidnumber')),
                ('domain', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='sipuser.domain')),
                ('extension', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='sipuser.extension')),
            ],
            options={
                'verbose_name': 'Call Detail Record',
                'verbose_name_plural': 'Call Detail Records',
                'db_table': 'fs_cdr',
                'managed': True,
            },
        ),
    ]
