# Generated by Django 3.2.7 on 2022-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0009_fscdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscdr',
            name='domain_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fscdr',
            name='hangup_cause',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fscdr',
            name='recording_file',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fscdr',
            name='bill_duration',
            field=models.IntegerField(default=0, verbose_name='call duration'),
        ),
    ]
