# Generated by Django 3.2.7 on 2022-06-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0010_auto_20220619_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscdr',
            name='in_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fscdr',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
