# Generated by Django 3.2.7 on 2022-07-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0011_auto_20220620_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscdr',
            name='caller_carrier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fscdr',
            name='caller_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
