# Generated by Django 3.2.7 on 2022-06-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0011_auto_20220620_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='cellphone',
            field=models.CharField(default='', max_length=20, verbose_name='Forwarding number'),
        ),
    ]
