# Generated by Django 3.2.7 on 2022-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0012_extension_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('didnumber', models.CharField(max_length=20, verbose_name='OneUp Number')),
                ('target_number', models.CharField(max_length=20, verbose_name='Target Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Bridge Call',
                'verbose_name_plural': 'Bridge Calls',
                'db_table': 'fs_bridge_call',
                'managed': True,
            },
        ),
    ]
