# Generated by Django 3.2.7 on 2022-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0013_bridgecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgecall',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
