# Generated by Django 3.2.7 on 2022-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0013_fscdr_captcha_verified'),
        ('sipuser', '0014_bridgecall_active'),
    ]

    operations = [
    ]
