# Generated by Django 3.2.7 on 2022-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0015_merge_20220707_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridgecall',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bridgecall',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bridgecall',
            name='timeout',
            field=models.IntegerField(default=5),
        ),
    ]
