# Generated by Django 3.2.7 on 2022-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0016_auto_20220707_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='transcription',
            field=models.IntegerField(default=0),
        ),
    ]
