# Generated by Django 3.2.7 on 2022-08-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0017_extension_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsdidnumber',
            name='extension',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='extension_didnumber', to='sipuser.extension'),
        ),
    ]
