# Generated by Django 3.2.7 on 2022-08-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0018_alter_fsdidnumber_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscdr',
            name='transcription_text',
            field=models.TextField(null=True),
        ),
    ]
