# Generated by Django 3.2.7 on 2022-08-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sipuser', '0019_fscdr_transcription_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=10, verbose_name='Conference PIN')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('didnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_didnumber', to='sipuser.fsdidnumber')),
            ],
            options={
                'verbose_name': 'Conference Room',
                'verbose_name_plural': 'Conference Room',
                'db_table': 'conference_room',
                'managed': True,
            },
        ),
    ]
