# Generated by Django 3.2.7 on 2021-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Calling'), (1, 'Answered'), (2, 'Processed'), (3, 'Success'), (4, 'Failed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'CallLog',
                'verbose_name_plural': 'CallLogs',
                'db_table': 'call_logs',
                'managed': True,
            },
        ),
    ]
