# Generated by Django 3.2.7 on 2021-11-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_callkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callkey',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
