# Generated by Django 3.2.7 on 2021-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_callkey_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Calling'), (2, 'Answered'), (3, 'Processed'), (4, 'Success'), (5, 'Failed')], default=0),
        ),
    ]
