# Generated by Django 3.2.7 on 2021-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_calllog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='callkey',
            name='audio_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
