# Generated by Django 3.2.7 on 2021-12-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_callkey_audio_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='callkey',
            name='audio_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
