# Generated by Django 3.2.7 on 2021-12-08 05:33

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_callkey_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='usermedia')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calllog')),
            ],
            options={
                'verbose_name': 'CallMenu',
                'verbose_name_plural': 'CallMenus',
                'db_table': 'call_menu',
                'managed': True,
            },
        ),
    ]
