# Generated by Django 3.2.7 on 2021-12-08 06:20

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_callmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callmenu',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to=''),
        ),
    ]
