# Generated by Django 3.2.7 on 2021-12-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_callmenu_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='callmenu',
            name='audio_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
