# Generated by Django 3.2.7 on 2021-12-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_callmenu_audio_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='callkey',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.callmenu'),
        ),
    ]
