# Generated by Django 3.2.7 on 2021-12-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_callkey_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callkey',
            name='call',
        ),
    ]
