# Generated by Django 3.2.7 on 2021-12-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_callkey_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
