# Generated by Django 3.2.7 on 2021-12-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_callkey_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('business_name', models.TextField(blank=True, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Phonenumber',
                'verbose_name_plural': 'Phonenumbers',
                'db_table': 'phone_numbers',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='callkey',
            name='level',
        ),
        migrations.RemoveField(
            model_name='callkey',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='business_name',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber'),
        ),
    ]
