# Generated by Django 3.2.7 on 2021-12-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211219_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
