# Generated by Django 3.2.7 on 2021-12-21 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_phonenumber_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callkey',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='api.callmenu'),
        ),
    ]
