# Generated by Django 3.2.7 on 2022-02-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220129_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='callmenu',
            name='audio_text_debug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
