# Generated by Django 3.2.7 on 2022-02-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_callmenu_audio_text_debug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Calling'), (2, 'Answered'), (3, 'Processed'), (4, 'Success'), (5, 'Failed')], default=0)),
                ('forwarding_number', models.CharField(max_length=250)),
                ('audio_file', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.callmenu')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonenumber')),
            ],
            options={
                'verbose_name': 'Agent Call Log',
                'verbose_name_plural': 'Agent Call Logs',
                'db_table': 'agentcall_logs',
                'managed': True,
            },
        ),
    ]
