# Generated by Django 3.2.7 on 2022-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_agentcalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_to', models.CharField(max_length=20)),
                ('sms_body', models.CharField(max_length=140)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sms_result', models.TextField(blank=True, max_length=500, null=True)),
                ('sms_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'db_table': 'sms_logs',
                'managed': True,
            },
        ),
    ]
