# Generated by Django 3.2.7 on 2022-06-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sipuser', '0010_auto_20220619_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Phonebook Nmae')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook_extension', to='sipuser.extension')),
            ],
            options={
                'verbose_name': 'Phonebook',
                'verbose_name_plural': 'Phonebook',
                'db_table': 'phonebooks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=50, unique=True, verbose_name='Phonenumber')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_phonebook', to='contacts.phonebook')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'managed': True,
            },
        ),
    ]
