# Generated by Django 3.2.7 on 2022-06-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='source',
            field=models.CharField(choices=[('API', 'api'), ('CAPTCHA', 'captcha'), ('OUTBOUND', 'outbound')], default='API', max_length=10),
        ),
    ]
