# Generated by Django 3.2.7 on 2022-06-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phonenumber',
            field=models.CharField(max_length=50, verbose_name='Phonenumber'),
        ),
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together={('phonebook', 'phonenumber')},
        ),
    ]
