# Generated by Django 3.2.7 on 2022-06-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_phonebook_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='source',
            field=models.CharField(choices=[('api', 'api'), ('captcha', 'captcha'), ('outbound', 'outbound')], default='API', max_length=10),
        ),
    ]
