# Generated by Django 3.2.7 on 2022-07-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contacts_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Phonenumber')),
                ('caller_type', models.CharField(default='', max_length=100)),
                ('caller_carrier', models.CharField(default='', max_length=100)),
                ('carrier_expired', models.DateTimeField(null=True)),
                ('spam_risk', models.IntegerField(default=0)),
                ('fraud_risk', models.IntegerField(default=0)),
                ('unlawful_risk', models.IntegerField(default=0)),
                ('spam_expired', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Inbound Number',
                'verbose_name_plural': 'Inbound Numbers',
                'db_table': 'inbound_number',
                'managed': True,
            },
        ),
    ]
